### ISSUE TITLE
Download link doesn't work

### ISSUE THREAD

**Issue by jameshunterbr** [rstudio-education/ymlthis#1]
Your download link in the new site: remotes::install_github("rstudio-education/ymlthis") doesn't work. It reports 404-file not found. Could you correct the reference in your new site (https://r-lib.github.io/ymlthis/), please. Thanks.

**Comment by malcolmbarrett** [comment]
Sorry, I didn't see this, but this was updated in the meantime

**Comment by jameshunterbr** [comment]
Thanks. 

⁣Get BlueMail for Android ​
